In [13]:
df = pandas.read_json("supermarkets.json")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [14]:
df2= pandas.read_excel("supermarkets.xlsx")
df2

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [15]:
df3 = pandas.read_excel("supermarkets.xlsx", sheet = 0)
df3

TypeError: read_excel() got an unexpected keyword argument `sheet`

In [16]:
df3 = pandas.read_excel("supermarkets.xlsx",sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [18]:
df4 = pandas.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [20]:
df5 = pandas.read_csv("supermarkets_semi-colons.txt",separator=";")
df5

TypeError: parser_f() got an unexpected keyword argument 'separator'

In [21]:
pandas.read_csv?


In [25]:
df5 = pandas.read_csv("supermarkets-semi-colons.txt",sep = ";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [28]:
df6 =  pandas.read_csv("data.csv", header = None)
df6

0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [29]:
df6.columns = ["ID", "Direccion", "Ciudad", "ZipCode", "Pais", "Nombre", "Num Empleados"]
df6

ID        Direccion         Ciudad           ZipCode Pais       Nombre  \
0   1     3666 21st St  San Francisco          CA 94114  USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114  USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California  USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

   Num Empleados  
0              8  
1             15  
2             25  
3             10  
4             12  
5             20

In [30]:
df7 = df6.set_index("ID")
df7

Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados  
ID                 
1               8  
2              15  
3              25  
4              10  
5              12  
6              20

In [41]:
df7.loc["2":"4","Ciudad":"Nombre"]


Ciudad           ZipCode Pais       Nombre
ID                                                   
2   San Francisco          CA 94119  USA  Bready Shop
3   San Francisco  California 94114  USA  Super River
4   San Francisco          CA 94114  USA   Ben's Shop

In [43]:
df7.iloc[1:4,1:3]


Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                      
2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3      332 Hill St  San Francisco  California 94114  USA  Super River   
4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   

    Num Empleados  
ID                 
2              15  
3              25  
4              10

In [46]:
df7.iloc[1:4,1:3]

Ciudad           ZipCode
ID                                 
2   San Francisco          CA 94119
3   San Francisco  California 94114
4   San Francisco          CA 94114

In [47]:
df7.iloc[3,3]

'USA'

In [48]:
df7.iloc[:,3]

ID
1    USA
2    USA
3    USA
4    USA
5    USA
6    USA
Name: Pais, dtype: object

In [50]:
ls = list(df7.iloc[:,4])
print(ls)


['Madeira', 'Bready Shop', 'Super River', "Ben's Shop", 'Sanchez', 'Richvalley']


In [51]:
df7.drop("Ciudad",1)


Direccion           ZipCode Pais       Nombre  Num Empleados
ID                                                                    
1      3666 21st St          CA 94114  USA      Madeira              8
2    735 Dolores St          CA 94119  USA  Bready Shop             15
3       332 Hill St  California 94114  USA  Super River             25
4      3995 23rd St          CA 94114  USA   Ben's Shop             10
5   1056 Sanchez St        California  USA      Sanchez             12
6   551 Alvarado St          CA 94114  USA   Richvalley             20

In [52]:
df7


Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados  
ID                 
1               8  
2              15  
3              25  
4              10  
5              12  
6              20

In [55]:
df7.drop(3,0)

Direccion         Ciudad     ZipCode Pais       Nombre  \
ID                                                                 
1      3666 21st St  San Francisco    CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco    CA 94119  USA  Bready Shop   
4      3995 23rd St  San Francisco    CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco  California  USA      Sanchez   
6   551 Alvarado St  San Francisco    CA 94114  USA   Richvalley   

    Num Empleados  
ID                 
1               8  
2              15  
4              10  
5              12  
6              20

In [56]:
df7

Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados  
ID                 
1               8  
2              15  
3              25  
4              10  
5              12  
6              20

In [57]:
df7.drop(df7.index[0:3])


Direccion         Ciudad     ZipCode Pais      Nombre  Num Empleados
ID                                                                            
4      3995 23rd St  San Francisco    CA 94114  USA  Ben's Shop             10
5   1056 Sanchez St  San Francisco  California  USA     Sanchez             12
6   551 Alvarado St  San Francisco    CA 94114  USA  Richvalley             20

In [58]:
df7.drop(df7.columns[0:2],1)

ZipCode Pais       Nombre  Num Empleados
ID                                                   
1           CA 94114  USA      Madeira              8
2           CA 94119  USA  Bready Shop             15
3   California 94114  USA  Super River             25
4           CA 94114  USA   Ben's Shop             10
5         California  USA      Sanchez             12
6           CA 94114  USA   Richvalley             20

In [59]:
df7["Continente"] = df7.shape[0]*["AmericaDelNorte"]

In [60]:
df7


Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados       Continente  
ID                                  
1               8  AmericaDelNorte  
2              15  AmericaDelNorte  
3              25  AmericaDelNorte  
4              10  AmericaDelNorte  
5              12  AmericaDelNorte  
6              20  AmericaDelNorte

In [63]:
df7.shape[0]

6

In [64]:
df7.shape[0]*["NorteAmrica"]

['NorteAmrica',
 'NorteAmrica',
 'NorteAmrica',
 'NorteAmrica',
 'NorteAmrica',
 'NorteAmrica']

In [65]:
df7


Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados       Continente  
ID                                  
1               8  AmericaDelNorte  
2              15  AmericaDelNorte  
3              25  AmericaDelNorte  
4              10  AmericaDelNorte  
5              12  AmericaDelNorte  
6              20  AmericaDelNorte

In [68]:
df7["Continente"] = df7["Pais"] + " , " + ["NorteAmerica"]

In [69]:
df7

Direccion         Ciudad           ZipCode Pais       Nombre  \
ID                                                                       
1      3666 21st St  San Francisco          CA 94114  USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119  USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114  USA  Super River   
4      3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California  USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114  USA   Richvalley   

    Num Empleados          Continente  
ID                                     
1               8  USA , NorteAmerica  
2              15  USA , NorteAmerica  
3              25  USA , NorteAmerica  
4              10  USA , NorteAmerica  
5              12  USA , NorteAmerica  
6              20  USA , NorteAmerica

In [73]:
df7_t = df7.T

In [74]:
df7_t


ID                              1                   2                   3  \
Direccion            3666 21st St      735 Dolores St         332 Hill St   
Ciudad              San Francisco       San Francisco       San Francisco   
ZipCode                  CA 94114            CA 94119    California 94114   
Pais                          USA                 USA                 USA   
Nombre                    Madeira         Bready Shop         Super River   
Num Empleados                   8                  15                  25   
Continente     USA , NorteAmerica  USA , NorteAmerica  USA , NorteAmerica   

ID                              4                   5                   6  
Direccion            3995 23rd St     1056 Sanchez St     551 Alvarado St  
Ciudad              San Francisco       San Francisco       San Francisco  
ZipCode                  CA 94114          California            CA 94114  
Pais                          USA                 USA                 USA  
Nombre                 Ben's Shop             Sanchez          Richvalley  
Num Empleados                  10                  12                  20  
Continente     USA , NorteAmerica  USA , NorteAmerica  USA , NorteAmerica

In [76]:
df7_t[7] = ["MiDireccion", "MiCiudad", "MiZipCode", "MiPais", "MiNombre", 10, "MiContinente"]


In [77]:
df7_t

ID                              1                   2                   3  \
Direccion            3666 21st St      735 Dolores St         332 Hill St   
Ciudad              San Francisco       San Francisco       San Francisco   
ZipCode                  CA 94114            CA 94119    California 94114   
Pais                          USA                 USA                 USA   
Nombre                    Madeira         Bready Shop         Super River   
Num Empleados                   8                  15                  25   
Continente     USA , NorteAmerica  USA , NorteAmerica  USA , NorteAmerica   

ID                              4                   5                   6  \
Direccion            3995 23rd St     1056 Sanchez St     551 Alvarado St   
Ciudad              San Francisco       San Francisco       San Francisco   
ZipCode                  CA 94114          California            CA 94114   
Pais                          USA                 USA                 USA   
Nombre                 Ben's Shop             Sanchez          Richvalley   
Num Empleados                  10                  12                  20   
Continente     USA , NorteAmerica  USA , NorteAmerica  USA , NorteAmerica   

ID                        7  
Direccion       MiDireccion  
Ciudad             MiCiudad  
ZipCode           MiZipCode  
Pais                 MiPais  
Nombre             MiNombre  
Num Empleados            10  
Continente     MiContinente

In [78]:
df7_t =df7_t.T

In [79]:
df7= df7_t


In [80]:
df7

Direccion         Ciudad           ZipCode    Pais       Nombre  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   
7       MiDireccion       MiCiudad         MiZipCode  MiPais     MiNombre   

   Num Empleados          Continente  
ID                                    
1              8  USA , NorteAmerica  
2             15  USA , NorteAmerica  
3             25  USA , NorteAmerica  
4             10  USA , NorteAmerica  
5             12  USA , NorteAmerica  
6             20  USA , NorteAmerica  
7             10        MiContinente

In [81]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'Geolake',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [86]:
from geopy.geocoders import ArcGIS


In [88]:
nom = ArcGIS()
n= nom.geocode("3666 21st St,San Francisco,CA 94114")

In [90]:
n.latitude

37.7564496899993

In [91]:
n.longitude

-122.42936434915458

In [93]:
import pandas 
df = pandas.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [94]:
df["DireccionCompleta"]=df["Address"] +" , " + df["City"] + " , " + df["State"]

In [95]:
df


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                               DireccionCompleta  
0          8         3666 21st St , San Francisco , CA 94114  
1         15       735 Dolores St , San Francisco , CA 94119  
2         25  332 Hill St , San Francisco , California 94114  
3         10         3995 23rd St , San Francisco , CA 94114  
4         12    1056 Sanchez St , San Francisco , California  
5         20      551 Alvarado St , San Francisco , CA 94114

In [106]:
df["Coordenada"]= df["DireccionCompleta"].apply(nom.geocode)

In [107]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                               DireccionCompleta  \
0          8         3666 21st St , San Francisco , CA 94114   
1         15       735 Dolores St , San Francisco , CA 94119   
2         25  332 Hill St , San Francisco , California 94114   
3         10         3995 23rd St , San Francisco , CA 94114   
4         12    1056 Sanchez St , San Francisco , California   
5         20      551 Alvarado St , San Francisco , CA 94114   

                                          Coordenada  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [108]:
df["latitud"] = df["Coordenada"].apply(lambda x: x.latitude if x !=None else None)

In [109]:
df["longitud"] = df["Coordenada"].apply(lambda x: x.longitude if x !=None else None)

In [110]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                               DireccionCompleta  \
0          8         3666 21st St , San Francisco , CA 94114   
1         15       735 Dolores St , San Francisco , CA 94119   
2         25  332 Hill St , San Francisco , California 94114   
3         10         3995 23rd St , San Francisco , CA 94114   
4         12    1056 Sanchez St , San Francisco , California   
5         20      551 Alvarado St , San Francisco , CA 94114   

                                          Coordenada    latitud    longitud  
0  (3666 21st St, San Francisco, California, 9411...  37.756450 -122.429364  
1  (735 Dolores St, San Francisco, California, 94...  37.757796 -122.425597  
2  (332 Hill St, San Francisco, California, 94114...  37.755648 -122.428803  
3  (3995 23rd St, San Francisco, California, 9411...  37.752991 -122.431702  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752129 -122.430028  
5  (551 Alvarado St, San Francisco, California, 9...  37.753719 -122.433240

In [124]:
df = df.drop(columns = "Coordenada")


In [126]:
df=df.drop(columns= "DireccionCompleta")

In [127]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees    latitud    longitud  
0          8  37.756450 -122.429364  
1         15  37.757796 -122.425597  
2         25  37.755648 -122.428803  
3         10  37.752991 -122.431702  
4         12  37.752129 -122.430028  
5         20  37.753719 -122.433240

In [30]:
import numpy
n =  numpy.arange(27)

In [131]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [133]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [136]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
m = numpy.asarray([[123,12,120,123,12],[],[]])


In [138]:
m

array([list([123, 12, 120, 123, 12]), list([]), list([])], dtype=object)

In [1]:
import cv2


In [12]:
im_g = cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
im_g2 = cv2.imread("smallgray.png",1)
im_g2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [8]:
cv2.imwrite("smallgray.png",im_g)

True

In [37]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [40]:
im_g.shape

(3, 5)

In [43]:
im_g[2,4]

182

In [45]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [47]:
cv2.imwrite("prueba.png", im_g.T)

True

In [49]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [52]:
ims = numpy.hstack((im_g,im_g))

In [54]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [56]:
cv2.imwrite("prueba2.png",ims)

True

In [60]:
koala = cv2.imread("koala.jpg",0)

In [62]:
koala


array([[ 90,  92,  96, ...,  93, 100,  88],
       [ 89,  95,  93, ...,  93,  97,  86],
       [ 95,  94,  95, ...,  93,  96,  92],
       ...,
       [211, 213, 210, ..., 125, 118, 123],
       [206, 200, 195, ..., 129, 123, 125],
       [203, 195, 189, ..., 123, 118, 124]], dtype=uint8)

In [66]:
koalaims= numpy.hstack((koala,koala))

In [68]:
cv2.imwrite("prueba2.png",koalaims)

True

In [71]:
cv2.imwrite("prueba3.png",koalaims.T)

True

In [155]:
import math
for i in koala:
    koala[i,i] = 0

    

In [159]:
koala

array([[  0, 122, 126, ..., 123, 130, 118],
       [119,   0, 123, ..., 123, 127, 116],
       [125, 124,   0, ..., 123, 126, 122],
       ...,
       [241, 243, 240, ..., 155, 148, 153],
       [236, 230, 225, ..., 159, 153, 155],
       [233, 225, 219, ..., 153, 148, 154]], dtype=uint8)

In [142]:
cv2.imwrite("prueba4.png",koala)

True